FROM node:21-alpine AS build

WORKDIR /app

COPY package*.json .

RUN npm install
COPY . .

RUN npm run build

FROM node:21-alpine

WORKDIR /app

COPY package*.json .
RUN npm install --only=production

COPY --from=build /app/dist ./dist
COPY --from=build /app/.env .

EXPOSE 5000 8080

CMD ["node", "dist/index.js"]
