FROM node:21-alpine

WORKDIR /app
COPY package*.json .
RUN apk update && apk add bash && apk add git
RUN npm install
COPY . .

RUN npm install -g typescript

EXPOSE 5000 8080

CMD ["npm", "run", "dev"]
